import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.scss";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Costa Rica Course",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
